### PR TITLE
Add contribution guidelines

### LINKED ISSUE #41: Add contribution guideline
If we move the contribution guideline to separate file [a link to it would be displayed if an issue or pull request is created](https://github.com/blog/1184-contributing-guidelines).

### PR DESCRIPTION
**Pull request by rm--**
The are two guidelines:
1. for cookiecutter-django-project itself
2. for project that is created with cookiecutter

Fixes #41.

### CODE REVIEW

**Comment by rm--** [comment]
Resolves #41.

**Comment by rm--** [comment]
I also added a new `cookiecutter template variable` with the name `github_account` which has as default value `transcode-de`. This new variable is necessary for github links that pointing e.g. to issues.

**Comment by DebVortex** [comment]
Fine for me.

**Comment by keimlink** [comment]
Thanks @rm--!

**Pull request merged**
