### PR TITLE
Made admin setting dynamic

### LINKED ISSUE #44: Make admin value in settings dynamic
In the common.py, the `ADMIN` setting is set to `('transcode', 'traceback@transcode.de')`.

This should be set during creation of the project, instead of settings the transcode value.

### PR DESCRIPTION
**Pull request by DebVortex**
Fixes #44.

### CODE REVIEW

**Comment by keimlink** [comment]
`cookiecutter.email` is used in `setup.py` and may be different from the email address being used for errors/trackbacks. Maybe introduce a new setting?

**Comment by DebVortex** [comment]
Fine for me. Should we also add another string for the name?

**Comment by keimlink** [comment]
The name is fine in my opinion. Usually users will change or extend the `ADMINS` list. Therefore we could use a django-configuration value.

**Comment by DebVortex** [comment]
A configuration value to force the user adding something instead of presetting something?

**Comment by keimlink** [comment]
No, using the current tuple as default. But allowing an easy change of `ADMINS` using an environment variable.

**Comment by DebVortex** [comment]
Done. I added an additional TupleValue for the admin setting.

**Comment by keimlink** [comment]
Thanks for adding the `TupleValue`. 😀

In my opinion it would make sense to have a separate cookiecutter setting for the email address errors are sent to. So instead of using `cookiecutter.email` in `ADMINS` a `cookiecutter.error_email` setting should be added and used.

**Comment by rm--** [comment]
Fixes #44.

**Comment by rm--** [comment]
Fine for me.

**Pull request merged**
